#!/usr/bin/env python3
"""Offline W2 retraining (NumPy) using hidden spike features, then export hardware weights.

Pipeline:
1. Read SMEM CSV with spike_h* columns (generated by snn_torch_infer_and_dump.py --train).
2. Build one feature vector per sample from hidden spike counts.
3. Train a multinomial softmax classifier (W2 only, no bias) offline.
4. Quantize trained W2 into int range [-100, 100] and write best_weights_hw-style file,
   preserving W1 from input weights.

This is an offline optimization flow and avoids in-place heuristic blame updates.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import struct
import urllib.request
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np

INPUT_SIZE = 784
HIDDEN_SIZE = 200
OUTPUT_SIZE = 10

W2_MIN = -100
W2_MAX = 100

_MNIST_URLS = {
    "train-images-idx3-ubyte.gz": "https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz",
    "train-labels-idx1-ubyte.gz": "https://storage.googleapis.com/cvdf-datasets/mnist/train-labels-idx1-ubyte.gz",
}

_MNIST_MIRRORS: dict[str, list[str]] = {
    k: [
        _MNIST_URLS[k],
        f"http://yann.lecun.com/exdb/mnist/{k}",
    ]
    for k in _MNIST_URLS
}


def _download_file(filename: str, dest: Path) -> None:
    for url in _MNIST_MIRRORS[filename]:
        try:
            print(f"  Downloading {filename} from {url} ...")
            urllib.request.urlretrieve(url, dest)
            print(f"  Saved to {dest}")
            return
        except Exception as exc:
            print(f"  Failed ({exc}), trying next mirror...")
    raise RuntimeError(f"Could not download {filename} from any mirror.")


def load_mnist_labels(path: Path) -> np.ndarray:
    with gzip.open(path, "rb") as f:
        magic, n = struct.unpack(">2I", f.read(8))
        if magic != 0x00000801:
            raise ValueError(f"Bad label magic {magic:#x} in {path}")
        labels = np.frombuffer(f.read(), dtype=np.uint8)
    if len(labels) != n:
        raise ValueError(f"Label length mismatch for {path}")
    return labels


def get_train_labels(data_root: Path) -> np.ndarray:
    data_root.mkdir(parents=True, exist_ok=True)
    label_name = "train-labels-idx1-ubyte.gz"
    label_path = data_root / label_name
    if not label_path.exists():
        _download_file(label_name, label_path)
    return load_mnist_labels(label_path)


def parse_weight_file(path: Path) -> Tuple[List[List[int]], List[List[int]]]:
    w1: List[List[int]] = []
    w2: List[List[int]] = []
    section = None

    with path.open("r", encoding="utf-8", errors="ignore") as f:
        for raw in f:
            line = raw.strip()
            if not line:
                continue
            if line.startswith("W1 Weights"):
                section = "w1"
                continue
            if line.startswith("W2 Weights"):
                section = "w2"
                continue
            if set(line) <= {"-"}:
                continue
            if section is None:
                continue

            toks = line.replace(",", " ").split()
            try:
                row = [int(x) for x in toks]
            except ValueError:
                continue

            if section == "w1":
                w1.append(row)
            else:
                w2.append(row)

    if len(w1) != INPUT_SIZE or any(len(r) != HIDDEN_SIZE for r in w1):
        raise ValueError("W1 shape mismatch")
    if len(w2) != HIDDEN_SIZE or any(len(r) != OUTPUT_SIZE for r in w2):
        raise ValueError("W2 shape mismatch")

    return w1, w2


def write_weight_file(path: Path, w1: List[List[int]], w2: List[List[int]]) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("W1 Weights (784 x 200):\n")
        for row in w1:
            f.write(" ".join(str(x) for x in row) + "\n")
        f.write("\n-------------------------------------\n\n")
        f.write("W2 Weights (200 x 10):\n")
        for row in w2:
            f.write(" ".join(str(x) for x in row) + "\n")


def load_hidden_features_from_smem(smem_csv: Path) -> Tuple[np.ndarray, np.ndarray]:
    """Return X (n,200) spike-count features and sample_ids (n,)."""
    feature_by_sample: Dict[int, np.ndarray] = {}

    with smem_csv.open("r", newline="", encoding="utf-8", errors="ignore") as f:
        reader = csv.DictReader(f)
        req = ["sample", "ts"] + [f"spike_h{i}" for i in range(HIDDEN_SIZE)]
        for col in req:
            if col not in (reader.fieldnames or []):
                raise ValueError(f"Missing required SMEM column: {col}")

        for row in reader:
            sample = int(row["sample"])
            if sample not in feature_by_sample:
                feature_by_sample[sample] = np.zeros(HIDDEN_SIZE, dtype=np.float32)
            vec = feature_by_sample[sample]
            for i in range(HIDDEN_SIZE):
                vec[i] += float(int(row[f"spike_h{i}"]))

    if not feature_by_sample:
        raise ValueError("No sample rows found in SMEM CSV")

    sample_ids = np.array(sorted(feature_by_sample.keys()), dtype=np.int32)
    X = np.stack([feature_by_sample[s] for s in sample_ids], axis=0)
    return X, sample_ids


def softmax(logits: np.ndarray) -> np.ndarray:
    z = logits - np.max(logits, axis=1, keepdims=True)
    e = np.exp(z)
    return e / np.sum(e, axis=1, keepdims=True)


def train_softmax_w2(
    X: np.ndarray,
    y: np.ndarray,
    epochs: int,
    lr: float,
    weight_decay: float,
    batch_size: int,
    seed: int,
    init_w: np.ndarray | None,
    anchor_l2: float,
) -> np.ndarray:
    rng = np.random.default_rng(seed)
    n, d = X.shape
    k = OUTPUT_SIZE

    if init_w is None:
        W = np.zeros((d, k), dtype=np.float32)
        W_anchor = np.zeros((d, k), dtype=np.float32)
    else:
        if init_w.shape != (d, k):
            raise ValueError(f"init_w shape mismatch, expected {(d, k)}, got {init_w.shape}")
        W = init_w.astype(np.float32).copy()
        W_anchor = init_w.astype(np.float32).copy()

    indices = np.arange(n)
    for ep in range(1, epochs + 1):
        rng.shuffle(indices)
        Xs = X[indices]
        ys = y[indices]

        for start in range(0, n, batch_size):
            end = min(start + batch_size, n)
            xb = Xs[start:end]
            yb = ys[start:end]

            probs = softmax(xb @ W)
            probs[np.arange(len(yb)), yb] -= 1.0
            grad = (xb.T @ probs) / float(len(yb))
            if weight_decay > 0:
                grad += weight_decay * W
            if anchor_l2 > 0:
                grad += anchor_l2 * (W - W_anchor)
            W -= lr * grad

        if ep == 1 or ep % 5 == 0 or ep == epochs:
            probs_all = softmax(X @ W)
            pred = np.argmax(probs_all, axis=1)
            acc = float(np.mean(pred == y) * 100.0)
            nll = -np.log(np.clip(probs_all[np.arange(n), y], 1e-9, 1.0)).mean()
            print(f"  epoch {ep:3d}/{epochs}  train_acc={acc:6.2f}%  nll={nll:.4f}")

    return W


def quantize_w2(W: np.ndarray, target_abs: float) -> Tuple[np.ndarray, float]:
    abs_vals = np.abs(W.reshape(-1))
    ref = float(np.percentile(abs_vals, 99.0)) if abs_vals.size else 0.0
    if ref <= 1e-12:
        scale = 1.0
    else:
        scale = target_abs / ref

    Wq = np.round(W * scale).astype(np.int32)
    Wq = np.clip(Wq, W2_MIN, W2_MAX)
    return Wq, scale


def main() -> None:
    parser = argparse.ArgumentParser(description="Offline W2 retraining + hardware export (NumPy)")
    parser.add_argument("--weights-in", type=Path, required=True, help="Input best_weights_hw.txt")
    parser.add_argument("--smem-train", type=Path, required=True, help="Train SMEM CSV (with spike_h*)")
    parser.add_argument("--weights-out", type=Path, required=True, help="Output best_weights_hw.txt")
    parser.add_argument("--data-root", type=Path, default=Path("./data"), help="MNIST IDX root")
    parser.add_argument("--epochs", type=int, default=40, help="Training epochs")
    parser.add_argument("--lr", type=float, default=0.2, help="Learning rate")
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="L2 weight decay")
    parser.add_argument("--batch-size", type=int, default=256, help="Mini-batch size")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument(
        "--from-scratch",
        action="store_true",
        help="Train W2 from zeros (legacy mode). Default is baseline-anchored fine-tuning.",
    )
    parser.add_argument(
        "--anchor-l2",
        type=float,
        default=0.01,
        help="L2 penalty on (W2 - baseline_W2) during anchored fine-tuning (default: 0.01)",
    )
    parser.add_argument(
        "--max-delta-per-weight",
        type=int,
        default=8,
        help="Max absolute per-weight delta from baseline W2 in anchored mode (default: 8)",
    )
    parser.add_argument(
        "--feature-norm",
        type=float,
        default=16.0,
        help="Divide spike-count features by this value (default: 16 timesteps)",
    )
    parser.add_argument(
        "--target-abs",
        type=float,
        default=80.0,
        help="Target 99th-percentile absolute value before clip to [-100,100]",
    )
    args = parser.parse_args()

    if args.epochs <= 0:
        raise ValueError("--epochs must be > 0")
    if args.lr <= 0:
        raise ValueError("--lr must be > 0")
    if args.batch_size <= 0:
        raise ValueError("--batch-size must be > 0")
    if args.feature_norm <= 0:
        raise ValueError("--feature-norm must be > 0")
    if args.target_abs <= 0:
        raise ValueError("--target-abs must be > 0")

    print(f"Loading baseline weights: {args.weights_in}")
    w1, w2_base = parse_weight_file(args.weights_in)

    print(f"Loading hidden features from SMEM: {args.smem_train}")
    X_counts, sample_ids = load_hidden_features_from_smem(args.smem_train)
    X = (X_counts / float(args.feature_norm)).astype(np.float32)

    print(f"Loading MNIST train labels from: {args.data_root}")
    labels = get_train_labels(args.data_root)
    if int(sample_ids[-1]) >= len(labels):
        raise ValueError("SMEM sample ids exceed MNIST train label range")
    y = labels[sample_ids].astype(np.int64)

    if args.anchor_l2 < 0:
        raise ValueError("--anchor-l2 must be >= 0")
    if args.max_delta_per_weight < 0:
        raise ValueError("--max-delta-per-weight must be >= 0")

    print(f"Training samples: {len(sample_ids)}")
    mode = "from-scratch" if args.from_scratch else "anchored-finetune"
    print(f"Training offline softmax W2 ({mode})...")
    w2_base_np = np.array(w2_base, dtype=np.float32)
    init_w = None if args.from_scratch else w2_base_np
    W_float = train_softmax_w2(
        X=X,
        y=y,
        epochs=args.epochs,
        lr=args.lr,
        weight_decay=args.weight_decay,
        batch_size=args.batch_size,
        seed=args.seed,
        init_w=init_w,
        anchor_l2=args.anchor_l2,
    )

    if args.from_scratch:
        W_q, scale = quantize_w2(W_float, args.target_abs)
    else:
        scale = 1.0
        base_int = np.array(w2_base, dtype=np.int32)
        cand_int = np.round(W_float).astype(np.int32)
        if args.max_delta_per_weight > 0:
            dmax = int(args.max_delta_per_weight)
            delta = np.clip(cand_int - base_int, -dmax, dmax)
            cand_int = base_int + delta
        W_q = np.clip(cand_int, W2_MIN, W2_MAX)

    w2_out = W_q.astype(int).tolist()

    args.weights_out.parent.mkdir(parents=True, exist_ok=True)
    write_weight_file(args.weights_out, w1, w2_out)

    print("\nDone.")
    print(f"  Mode               : {mode}")
    print(f"  Quantization scale : {scale:.6f}")
    if not args.from_scratch:
        print(f"  Anchor L2          : {args.anchor_l2}")
        print(f"  Max |delta|/weight : {args.max_delta_per_weight}")
    print(f"  W2 clip range      : [{W2_MIN}, {W2_MAX}]")
    print(f"  Exported weights   : {args.weights_out}")


if __name__ == "__main__":
    main()
