`timescale 1ns/100ps

// =============================================================================
//  surrogate_lut_wb.v — Surrogate Gradient Lookup Table (Wishbone Slave)
//  Project: On-Chip Offline Neuromorphic Computing (FYP)
// =============================================================================
//
//  Description:
//      A read-only 256-entry ROM that maps 8-bit membrane potential values
//      to their pre-calculated fast sigmoid surrogate gradient equivalents.
//
//      Used during STATE 2 (Surrogate Substitution):
//          - CPU reads V_mem from data memory
//          - CPU queries this LUT using V_mem as address index
//          - CPU writes returned surrogate gradient back to same memory location
//          - STATE 3 (Learning) then reads surrogate values directly → no
//            runtime surrogate computation needed
//
//  Surrogate Function:
//      h(v) = 1 / (1 + k * |v / 128|)^2,  k=4.0
//      Output: 8-bit unsigned fixed-point, 0xFF = 1.0 (peak at v=0)
//
//  Address Scheme (Wishbone):
//      CPU uses V_mem (8-bit unsigned) as word-offset into this peripheral.
//      To query LUT for membrane potential v_mem:
//          wb_addr = BASE_ADDR + (v_mem_unsigned * 4)
//      Note: v_mem stored in memory is treated as raw 8-bit (unsigned index).
//            Signed interpretation is embedded in the pre-calculated values.
//
//  LUT Index → Signed V_mem mapping:
//      Index   0   = v_mem =    0  (peak, grad = 1.0)
//      Index   1   = v_mem =   +1
//      ...
//      Index 127   = v_mem =  +127
//      Index 128   = v_mem =  -128
//      ...
//      Index 255   = v_mem =   -1  (near-peak, grad ≈ 0.94)
//
//  Wishbone Interface: Classic (non-pipelined), single-cycle ACK
//  Bus Width: 32-bit (surrogate value returned in bits [7:0])
//  Writes: ignored but ACK returned (peripheral is read-only)
//
//  Parameters:
//      BASE_ADDR — base address of this peripheral in the SoC address map
//                  (1 KB aligned: lower 10 bits must be zero)
// =============================================================================

module surrogate_lut_wb #(
    parameter [31:0] BASE_ADDR = 32'hA000_0000   // override in SoC integration
)(
    // ---- Wishbone Classic Slave Interface ----
    input  wire        wb_clk_i,
    input  wire        wb_rst_i,
    input  wire [31:0] wb_adr_i,   // Address from master
    input  wire [31:0] wb_dat_i,   // Data in  (ignored — read-only peripheral)
    input  wire  [3:0] wb_sel_i,   // Byte select (unused, always full word)
    input  wire        wb_we_i,    // Write enable
    input  wire        wb_stb_i,   // Strobe
    input  wire        wb_cyc_i,   // Bus cycle valid
    output reg  [31:0] wb_dat_o,   // Data out — surrogate gradient in [7:0]
    output reg         wb_ack_o    // Acknowledge
);

    // -------------------------------------------------------------------------
    //  ROM Declaration — 256 × 8-bit
    //  Synthesis tools (Vivado/Quartus) infer this as LUTRAM or Block RAM.
    //  The initial block is supported for ROM inference in synthesis.
    // -------------------------------------------------------------------------
    reg [7:0] lut_rom [0:255];

    initial begin
        // Values generated by gen_lut.py
        // h(v) = 1/(1 + 4*|v/128|)^2, scaled to uint8 (0xFF=1.0)
        // Index = raw 8-bit unsigned storage of V_mem
        lut_rom[  0] = 8'hFF;  // v =    0  grad ≈ 1.0000  ← PEAK
        lut_rom[  1] = 8'hF0;  // v =    1  grad ≈ 0.9412
        lut_rom[  2] = 8'hE2;  // v =    2  grad ≈ 0.8863
        lut_rom[  3] = 8'hD5;  // v =    3  grad ≈ 0.8353
        lut_rom[  4] = 8'hC9;  // v =    4  grad ≈ 0.7882
        lut_rom[  5] = 8'hBF;  // v =    5  grad ≈ 0.7490
        lut_rom[  6] = 8'hB5;  // v =    6  grad ≈ 0.7098
        lut_rom[  7] = 8'hAC;  // v =    7  grad ≈ 0.6745
        lut_rom[  8] = 8'hA3;  // v =    8  grad ≈ 0.6392
        lut_rom[  9] = 8'h9B;  // v =    9  grad ≈ 0.6078
        lut_rom[ 10] = 8'h94;  // v =   10  grad ≈ 0.5804
        lut_rom[ 11] = 8'h8D;  // v =   11  grad ≈ 0.5529
        lut_rom[ 12] = 8'h87;  // v =   12  grad ≈ 0.5294
        lut_rom[ 13] = 8'h81;  // v =   13  grad ≈ 0.5059
        lut_rom[ 14] = 8'h7B;  // v =   14  grad ≈ 0.4824
        lut_rom[ 15] = 8'h76;  // v =   15  grad ≈ 0.4627
        lut_rom[ 16] = 8'h71;  // v =   16  grad ≈ 0.4431
        lut_rom[ 17] = 8'h6D;  // v =   17  grad ≈ 0.4275
        lut_rom[ 18] = 8'h68;  // v =   18  grad ≈ 0.4078
        lut_rom[ 19] = 8'h64;  // v =   19  grad ≈ 0.3922
        lut_rom[ 20] = 8'h61;  // v =   20  grad ≈ 0.3804
        lut_rom[ 21] = 8'h5D;  // v =   21  grad ≈ 0.3647
        lut_rom[ 22] = 8'h5A;  // v =   22  grad ≈ 0.3529
        lut_rom[ 23] = 8'h56;  // v =   23  grad ≈ 0.3373
        lut_rom[ 24] = 8'h53;  // v =   24  grad ≈ 0.3255
        lut_rom[ 25] = 8'h50;  // v =   25  grad ≈ 0.3137
        lut_rom[ 26] = 8'h4E;  // v =   26  grad ≈ 0.3059
        lut_rom[ 27] = 8'h4B;  // v =   27  grad ≈ 0.2941
        lut_rom[ 28] = 8'h49;  // v =   28  grad ≈ 0.2863
        lut_rom[ 29] = 8'h46;  // v =   29  grad ≈ 0.2745
        lut_rom[ 30] = 8'h44;  // v =   30  grad ≈ 0.2667
        lut_rom[ 31] = 8'h42;  // v =   31  grad ≈ 0.2588
        lut_rom[ 32] = 8'h40;  // v =   32  grad ≈ 0.2510
        lut_rom[ 33] = 8'h3E;  // v =   33  grad ≈ 0.2431
        lut_rom[ 34] = 8'h3C;  // v =   34  grad ≈ 0.2353
        lut_rom[ 35] = 8'h3A;  // v =   35  grad ≈ 0.2275
        lut_rom[ 36] = 8'h38;  // v =   36  grad ≈ 0.2196
        lut_rom[ 37] = 8'h37;  // v =   37  grad ≈ 0.2157
        lut_rom[ 38] = 8'h35;  // v =   38  grad ≈ 0.2078
        lut_rom[ 39] = 8'h34;  // v =   39  grad ≈ 0.2039
        lut_rom[ 40] = 8'h32;  // v =   40  grad ≈ 0.1961
        lut_rom[ 41] = 8'h31;  // v =   41  grad ≈ 0.1922
        lut_rom[ 42] = 8'h30;  // v =   42  grad ≈ 0.1882
        lut_rom[ 43] = 8'h2E;  // v =   43  grad ≈ 0.1804
        lut_rom[ 44] = 8'h2D;  // v =   44  grad ≈ 0.1765
        lut_rom[ 45] = 8'h2C;  // v =   45  grad ≈ 0.1725
        lut_rom[ 46] = 8'h2B;  // v =   46  grad ≈ 0.1686
        lut_rom[ 47] = 8'h2A;  // v =   47  grad ≈ 0.1647
        lut_rom[ 48] = 8'h29;  // v =   48  grad ≈ 0.1608
        lut_rom[ 49] = 8'h28;  // v =   49  grad ≈ 0.1569
        lut_rom[ 50] = 8'h27;  // v =   50  grad ≈ 0.1529
        lut_rom[ 51] = 8'h26;  // v =   51  grad ≈ 0.1490
        lut_rom[ 52] = 8'h25;  // v =   52  grad ≈ 0.1451
        lut_rom[ 53] = 8'h24;  // v =   53  grad ≈ 0.1412
        lut_rom[ 54] = 8'h23;  // v =   54  grad ≈ 0.1373
        lut_rom[ 55] = 8'h22;  // v =   55  grad ≈ 0.1333
        lut_rom[ 56] = 8'h22;  // v =   56  grad ≈ 0.1333
        lut_rom[ 57] = 8'h21;  // v =   57  grad ≈ 0.1294
        lut_rom[ 58] = 8'h20;  // v =   58  grad ≈ 0.1255
        lut_rom[ 59] = 8'h20;  // v =   59  grad ≈ 0.1255
        lut_rom[ 60] = 8'h1F;  // v =   60  grad ≈ 0.1216
        lut_rom[ 61] = 8'h1E;  // v =   61  grad ≈ 0.1176
        lut_rom[ 62] = 8'h1E;  // v =   62  grad ≈ 0.1176
        lut_rom[ 63] = 8'h1D;  // v =   63  grad ≈ 0.1137
        lut_rom[ 64] = 8'h1C;  // v =   64  grad ≈ 0.1098
        lut_rom[ 65] = 8'h1C;  // v =   65  grad ≈ 0.1098
        lut_rom[ 66] = 8'h1B;  // v =   66  grad ≈ 0.1059
        lut_rom[ 67] = 8'h1B;  // v =   67  grad ≈ 0.1059
        lut_rom[ 68] = 8'h1A;  // v =   68  grad ≈ 0.1020
        lut_rom[ 69] = 8'h1A;  // v =   69  grad ≈ 0.1020
        lut_rom[ 70] = 8'h19;  // v =   70  grad ≈ 0.0980
        lut_rom[ 71] = 8'h19;  // v =   71  grad ≈ 0.0980
        lut_rom[ 72] = 8'h18;  // v =   72  grad ≈ 0.0941
        lut_rom[ 73] = 8'h18;  // v =   73  grad ≈ 0.0941
        lut_rom[ 74] = 8'h17;  // v =   74  grad ≈ 0.0902
        lut_rom[ 75] = 8'h17;  // v =   75  grad ≈ 0.0902
        lut_rom[ 76] = 8'h16;  // v =   76  grad ≈ 0.0863
        lut_rom[ 77] = 8'h16;  // v =   77  grad ≈ 0.0863
        lut_rom[ 78] = 8'h16;  // v =   78  grad ≈ 0.0863
        lut_rom[ 79] = 8'h15;  // v =   79  grad ≈ 0.0824
        lut_rom[ 80] = 8'h15;  // v =   80  grad ≈ 0.0824
        lut_rom[ 81] = 8'h14;  // v =   81  grad ≈ 0.0784
        lut_rom[ 82] = 8'h14;  // v =   82  grad ≈ 0.0784
        lut_rom[ 83] = 8'h14;  // v =   83  grad ≈ 0.0784
        lut_rom[ 84] = 8'h13;  // v =   84  grad ≈ 0.0745
        lut_rom[ 85] = 8'h13;  // v =   85  grad ≈ 0.0745
        lut_rom[ 86] = 8'h13;  // v =   86  grad ≈ 0.0745
        lut_rom[ 87] = 8'h12;  // v =   87  grad ≈ 0.0706
        lut_rom[ 88] = 8'h12;  // v =   88  grad ≈ 0.0706
        lut_rom[ 89] = 8'h12;  // v =   89  grad ≈ 0.0706
        lut_rom[ 90] = 8'h12;  // v =   90  grad ≈ 0.0706
        lut_rom[ 91] = 8'h11;  // v =   91  grad ≈ 0.0667
        lut_rom[ 92] = 8'h11;  // v =   92  grad ≈ 0.0667
        lut_rom[ 93] = 8'h11;  // v =   93  grad ≈ 0.0667
        lut_rom[ 94] = 8'h10;  // v =   94  grad ≈ 0.0627
        lut_rom[ 95] = 8'h10;  // v =   95  grad ≈ 0.0627
        lut_rom[ 96] = 8'h10;  // v =   96  grad ≈ 0.0627
        lut_rom[ 97] = 8'h10;  // v =   97  grad ≈ 0.0627
        lut_rom[ 98] = 8'h0F;  // v =   98  grad ≈ 0.0588
        lut_rom[ 99] = 8'h0F;  // v =   99  grad ≈ 0.0588
        lut_rom[100] = 8'h0F;  // v =  100  grad ≈ 0.0588
        lut_rom[101] = 8'h0F;  // v =  101  grad ≈ 0.0588
        lut_rom[102] = 8'h0F;  // v =  102  grad ≈ 0.0588
        lut_rom[103] = 8'h0E;  // v =  103  grad ≈ 0.0549
        lut_rom[104] = 8'h0E;  // v =  104  grad ≈ 0.0549
        lut_rom[105] = 8'h0E;  // v =  105  grad ≈ 0.0549
        lut_rom[106] = 8'h0E;  // v =  106  grad ≈ 0.0549
        lut_rom[107] = 8'h0E;  // v =  107  grad ≈ 0.0549
        lut_rom[108] = 8'h0D;  // v =  108  grad ≈ 0.0510
        lut_rom[109] = 8'h0D;  // v =  109  grad ≈ 0.0510
        lut_rom[110] = 8'h0D;  // v =  110  grad ≈ 0.0510
        lut_rom[111] = 8'h0D;  // v =  111  grad ≈ 0.0510
        lut_rom[112] = 8'h0D;  // v =  112  grad ≈ 0.0510
        lut_rom[113] = 8'h0C;  // v =  113  grad ≈ 0.0471
        lut_rom[114] = 8'h0C;  // v =  114  grad ≈ 0.0471
        lut_rom[115] = 8'h0C;  // v =  115  grad ≈ 0.0471
        lut_rom[116] = 8'h0C;  // v =  116  grad ≈ 0.0471
        lut_rom[117] = 8'h0C;  // v =  117  grad ≈ 0.0471
        lut_rom[118] = 8'h0C;  // v =  118  grad ≈ 0.0471
        lut_rom[119] = 8'h0B;  // v =  119  grad ≈ 0.0431
        lut_rom[120] = 8'h0B;  // v =  120  grad ≈ 0.0431
        lut_rom[121] = 8'h0B;  // v =  121  grad ≈ 0.0431
        lut_rom[122] = 8'h0B;  // v =  122  grad ≈ 0.0431
        lut_rom[123] = 8'h0B;  // v =  123  grad ≈ 0.0431
        lut_rom[124] = 8'h0B;  // v =  124  grad ≈ 0.0431
        lut_rom[125] = 8'h0B;  // v =  125  grad ≈ 0.0431
        lut_rom[126] = 8'h0A;  // v =  126  grad ≈ 0.0392
        lut_rom[127] = 8'h0A;  // v =  127  grad ≈ 0.0392
        lut_rom[128] = 8'h0A;  // v = -128  grad ≈ 0.0392
        lut_rom[129] = 8'h0A;  // v = -127  grad ≈ 0.0392
        lut_rom[130] = 8'h0A;  // v = -126  grad ≈ 0.0392
        lut_rom[131] = 8'h0B;  // v = -125  grad ≈ 0.0431
        lut_rom[132] = 8'h0B;  // v = -124  grad ≈ 0.0431
        lut_rom[133] = 8'h0B;  // v = -123  grad ≈ 0.0431
        lut_rom[134] = 8'h0B;  // v = -122  grad ≈ 0.0431
        lut_rom[135] = 8'h0B;  // v = -121  grad ≈ 0.0431
        lut_rom[136] = 8'h0B;  // v = -120  grad ≈ 0.0431
        lut_rom[137] = 8'h0B;  // v = -119  grad ≈ 0.0431
        lut_rom[138] = 8'h0C;  // v = -118  grad ≈ 0.0471
        lut_rom[139] = 8'h0C;  // v = -117  grad ≈ 0.0471
        lut_rom[140] = 8'h0C;  // v = -116  grad ≈ 0.0471
        lut_rom[141] = 8'h0C;  // v = -115  grad ≈ 0.0471
        lut_rom[142] = 8'h0C;  // v = -114  grad ≈ 0.0471
        lut_rom[143] = 8'h0C;  // v = -113  grad ≈ 0.0471
        lut_rom[144] = 8'h0D;  // v = -112  grad ≈ 0.0510
        lut_rom[145] = 8'h0D;  // v = -111  grad ≈ 0.0510
        lut_rom[146] = 8'h0D;  // v = -110  grad ≈ 0.0510
        lut_rom[147] = 8'h0D;  // v = -109  grad ≈ 0.0510
        lut_rom[148] = 8'h0D;  // v = -108  grad ≈ 0.0510
        lut_rom[149] = 8'h0E;  // v = -107  grad ≈ 0.0549
        lut_rom[150] = 8'h0E;  // v = -106  grad ≈ 0.0549
        lut_rom[151] = 8'h0E;  // v = -105  grad ≈ 0.0549
        lut_rom[152] = 8'h0E;  // v = -104  grad ≈ 0.0549
        lut_rom[153] = 8'h0E;  // v = -103  grad ≈ 0.0549
        lut_rom[154] = 8'h0F;  // v = -102  grad ≈ 0.0588
        lut_rom[155] = 8'h0F;  // v = -101  grad ≈ 0.0588
        lut_rom[156] = 8'h0F;  // v = -100  grad ≈ 0.0588
        lut_rom[157] = 8'h0F;  // v =  -99  grad ≈ 0.0588
        lut_rom[158] = 8'h0F;  // v =  -98  grad ≈ 0.0588
        lut_rom[159] = 8'h10;  // v =  -97  grad ≈ 0.0627
        lut_rom[160] = 8'h10;  // v =  -96  grad ≈ 0.0627
        lut_rom[161] = 8'h10;  // v =  -95  grad ≈ 0.0627
        lut_rom[162] = 8'h10;  // v =  -94  grad ≈ 0.0627
        lut_rom[163] = 8'h11;  // v =  -93  grad ≈ 0.0667
        lut_rom[164] = 8'h11;  // v =  -92  grad ≈ 0.0667
        lut_rom[165] = 8'h11;  // v =  -91  grad ≈ 0.0667
        lut_rom[166] = 8'h12;  // v =  -90  grad ≈ 0.0706
        lut_rom[167] = 8'h12;  // v =  -89  grad ≈ 0.0706
        lut_rom[168] = 8'h12;  // v =  -88  grad ≈ 0.0706
        lut_rom[169] = 8'h12;  // v =  -87  grad ≈ 0.0706
        lut_rom[170] = 8'h13;  // v =  -86  grad ≈ 0.0745
        lut_rom[171] = 8'h13;  // v =  -85  grad ≈ 0.0745
        lut_rom[172] = 8'h13;  // v =  -84  grad ≈ 0.0745
        lut_rom[173] = 8'h14;  // v =  -83  grad ≈ 0.0784
        lut_rom[174] = 8'h14;  // v =  -82  grad ≈ 0.0784
        lut_rom[175] = 8'h14;  // v =  -81  grad ≈ 0.0784
        lut_rom[176] = 8'h15;  // v =  -80  grad ≈ 0.0824
        lut_rom[177] = 8'h15;  // v =  -79  grad ≈ 0.0824
        lut_rom[178] = 8'h16;  // v =  -78  grad ≈ 0.0863
        lut_rom[179] = 8'h16;  // v =  -77  grad ≈ 0.0863
        lut_rom[180] = 8'h16;  // v =  -76  grad ≈ 0.0863
        lut_rom[181] = 8'h17;  // v =  -75  grad ≈ 0.0902
        lut_rom[182] = 8'h17;  // v =  -74  grad ≈ 0.0902
        lut_rom[183] = 8'h18;  // v =  -73  grad ≈ 0.0941
        lut_rom[184] = 8'h18;  // v =  -72  grad ≈ 0.0941
        lut_rom[185] = 8'h19;  // v =  -71  grad ≈ 0.0980
        lut_rom[186] = 8'h19;  // v =  -70  grad ≈ 0.0980
        lut_rom[187] = 8'h1A;  // v =  -69  grad ≈ 0.1020
        lut_rom[188] = 8'h1A;  // v =  -68  grad ≈ 0.1020
        lut_rom[189] = 8'h1B;  // v =  -67  grad ≈ 0.1059
        lut_rom[190] = 8'h1B;  // v =  -66  grad ≈ 0.1059
        lut_rom[191] = 8'h1C;  // v =  -65  grad ≈ 0.1098
        lut_rom[192] = 8'h1C;  // v =  -64  grad ≈ 0.1098
        lut_rom[193] = 8'h1D;  // v =  -63  grad ≈ 0.1137
        lut_rom[194] = 8'h1E;  // v =  -62  grad ≈ 0.1176
        lut_rom[195] = 8'h1E;  // v =  -61  grad ≈ 0.1176
        lut_rom[196] = 8'h1F;  // v =  -60  grad ≈ 0.1216
        lut_rom[197] = 8'h20;  // v =  -59  grad ≈ 0.1255
        lut_rom[198] = 8'h20;  // v =  -58  grad ≈ 0.1255
        lut_rom[199] = 8'h21;  // v =  -57  grad ≈ 0.1294
        lut_rom[200] = 8'h22;  // v =  -56  grad ≈ 0.1333
        lut_rom[201] = 8'h22;  // v =  -55  grad ≈ 0.1333
        lut_rom[202] = 8'h23;  // v =  -54  grad ≈ 0.1373
        lut_rom[203] = 8'h24;  // v =  -53  grad ≈ 0.1412
        lut_rom[204] = 8'h25;  // v =  -52  grad ≈ 0.1451
        lut_rom[205] = 8'h26;  // v =  -51  grad ≈ 0.1490
        lut_rom[206] = 8'h27;  // v =  -50  grad ≈ 0.1529
        lut_rom[207] = 8'h28;  // v =  -49  grad ≈ 0.1569
        lut_rom[208] = 8'h29;  // v =  -48  grad ≈ 0.1608
        lut_rom[209] = 8'h2A;  // v =  -47  grad ≈ 0.1647
        lut_rom[210] = 8'h2B;  // v =  -46  grad ≈ 0.1686
        lut_rom[211] = 8'h2C;  // v =  -45  grad ≈ 0.1725
        lut_rom[212] = 8'h2D;  // v =  -44  grad ≈ 0.1765
        lut_rom[213] = 8'h2E;  // v =  -43  grad ≈ 0.1804
        lut_rom[214] = 8'h30;  // v =  -42  grad ≈ 0.1882
        lut_rom[215] = 8'h31;  // v =  -41  grad ≈ 0.1922
        lut_rom[216] = 8'h32;  // v =  -40  grad ≈ 0.1961
        lut_rom[217] = 8'h34;  // v =  -39  grad ≈ 0.2039
        lut_rom[218] = 8'h35;  // v =  -38  grad ≈ 0.2078
        lut_rom[219] = 8'h37;  // v =  -37  grad ≈ 0.2157
        lut_rom[220] = 8'h38;  // v =  -36  grad ≈ 0.2196
        lut_rom[221] = 8'h3A;  // v =  -35  grad ≈ 0.2275
        lut_rom[222] = 8'h3C;  // v =  -34  grad ≈ 0.2353
        lut_rom[223] = 8'h3E;  // v =  -33  grad ≈ 0.2431
        lut_rom[224] = 8'h40;  // v =  -32  grad ≈ 0.2510
        lut_rom[225] = 8'h42;  // v =  -31  grad ≈ 0.2588
        lut_rom[226] = 8'h44;  // v =  -30  grad ≈ 0.2667
        lut_rom[227] = 8'h46;  // v =  -29  grad ≈ 0.2745
        lut_rom[228] = 8'h49;  // v =  -28  grad ≈ 0.2863
        lut_rom[229] = 8'h4B;  // v =  -27  grad ≈ 0.2941
        lut_rom[230] = 8'h4E;  // v =  -26  grad ≈ 0.3059
        lut_rom[231] = 8'h50;  // v =  -25  grad ≈ 0.3137
        lut_rom[232] = 8'h53;  // v =  -24  grad ≈ 0.3255
        lut_rom[233] = 8'h56;  // v =  -23  grad ≈ 0.3373
        lut_rom[234] = 8'h5A;  // v =  -22  grad ≈ 0.3529
        lut_rom[235] = 8'h5D;  // v =  -21  grad ≈ 0.3647
        lut_rom[236] = 8'h61;  // v =  -20  grad ≈ 0.3804
        lut_rom[237] = 8'h64;  // v =  -19  grad ≈ 0.3922
        lut_rom[238] = 8'h68;  // v =  -18  grad ≈ 0.4078
        lut_rom[239] = 8'h6D;  // v =  -17  grad ≈ 0.4275
        lut_rom[240] = 8'h71;  // v =  -16  grad ≈ 0.4431
        lut_rom[241] = 8'h76;  // v =  -15  grad ≈ 0.4627
        lut_rom[242] = 8'h7B;  // v =  -14  grad ≈ 0.4824
        lut_rom[243] = 8'h81;  // v =  -13  grad ≈ 0.5059
        lut_rom[244] = 8'h87;  // v =  -12  grad ≈ 0.5294
        lut_rom[245] = 8'h8D;  // v =  -11  grad ≈ 0.5529
        lut_rom[246] = 8'h94;  // v =  -10  grad ≈ 0.5804
        lut_rom[247] = 8'h9B;  // v =   -9  grad ≈ 0.6078
        lut_rom[248] = 8'hA3;  // v =   -8  grad ≈ 0.6392
        lut_rom[249] = 8'hAC;  // v =   -7  grad ≈ 0.6745
        lut_rom[250] = 8'hB5;  // v =   -6  grad ≈ 0.7098
        lut_rom[251] = 8'hBF;  // v =   -5  grad ≈ 0.7490
        lut_rom[252] = 8'hC9;  // v =   -4  grad ≈ 0.7882
        lut_rom[253] = 8'hD5;  // v =   -3  grad ≈ 0.8353
        lut_rom[254] = 8'hE2;  // v =   -2  grad ≈ 0.8863
        lut_rom[255] = 8'hF0;  // v =   -1  grad ≈ 0.9412
    end

    // -------------------------------------------------------------------------
    //  Address Decode
    //  The peripheral occupies a 1 KB window (256 words × 4 bytes).
    //  Upper bits [31:10] must match BASE_ADDR[31:10] for chip select.
    //  Bits [9:2] give the 8-bit LUT index (= raw V_mem byte).
    // -------------------------------------------------------------------------
    wire        cs      = wb_cyc_i & wb_stb_i &
                          (wb_adr_i[31:10] == BASE_ADDR[31:10]);
    wire [7:0]  lut_idx = wb_adr_i[9:2];   // word-aligned → strip lower 2 bits

    // -------------------------------------------------------------------------
    //  Wishbone Response — single clock cycle
    // -------------------------------------------------------------------------
    always @(posedge wb_clk_i) begin
        // Default: deassert ACK
        wb_ack_o <= 1'b0;
        wb_dat_o <= 32'h0000_0000;

        if (wb_rst_i) begin
            wb_ack_o <= 1'b0;
            wb_dat_o <= 32'h0000_0000;
        end
        else if (cs) begin
            if (!wb_we_i) begin
                // READ: return surrogate gradient in lower byte
                wb_dat_o <= {24'h000000, lut_rom[lut_idx]};
            end
            // WRITE: ignore dat_i, peripheral is read-only
            // ACK either way so master doesn't hang
            wb_ack_o <= 1'b1;
        end
    end

endmodule
